project_id = "srwbgkssoatrhxdrrtff"

[functions.building-regs-updater]
verify_jwt = false

[functions.building-regulations-chat]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-test-invitation]
verify_jwt = true

[functions.send-team-invitation]
verify_jwt = true

[functions.verify-in-app-purchase]
verify_jwt = true

[functions.analyze-drawing-scale]
verify_jwt = true

[functions.process-drawing-scale]
verify_jwt = false